In [64]:
#import hoston house-prices dataset
from sklearn.datasets import load_boston

In [65]:
#store the data in load variable
boston=load_boston()
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [66]:
#Data objects and target objects
X=boston.data
Y=boston.target

In [67]:
#Dimensions of data 
X.shape

(506, 13)

In [68]:
#Dimensions of target
Y.shape

(506,)

In [69]:
#To split the dataset into train data and test data
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.20,random_state=0)
X_train

array([[3.5809e-01, 0.0000e+00, 6.2000e+00, ..., 1.7400e+01, 3.9170e+02,
        9.7100e+00],
       [1.5876e-01, 0.0000e+00, 1.0810e+01, ..., 1.9200e+01, 3.7694e+02,
        9.8800e+00],
       [1.1329e-01, 3.0000e+01, 4.9300e+00, ..., 1.6600e+01, 3.9125e+02,
        1.1380e+01],
       ...,
       [1.5098e-01, 0.0000e+00, 1.0010e+01, ..., 1.7800e+01, 3.9451e+02,
        1.0300e+01],
       [2.2927e-01, 0.0000e+00, 6.9100e+00, ..., 1.7900e+01, 3.9274e+02,
        1.8800e+01],
       [1.3914e-01, 0.0000e+00, 4.0500e+00, ..., 1.6600e+01, 3.9690e+02,
        1.4690e+01]])

In [70]:
#To create a random array of size 10 with array values as male/female
import numpy as np
Y=np.random.choice(('Male','Female'),size=(10))
Y

array(['Female', 'Female', 'Female', 'Female', 'Female', 'Female', 'Male',
       'Male', 'Female', 'Female'], dtype='<U6')

In [71]:
#Encode the array values as 0 or 1
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
y=l.fit_transform(Y)
print(y)

[0 0 0 0 0 0 1 1 0 0]


In [72]:
#To replace the null values with mean values of respective column
#from sklearn.preprocessing import Imputer
from sklearn.impute import SimpleImputer
data=np.array([[1,np.nan,2],[2,3,np.nan],[-1,4,2]])
imp=SimpleImputer(strategy='mean')
imp.fit_transform(data)

array([[ 1. ,  3.5,  2. ],
       [ 2. ,  3. ,  2. ],
       [-1. ,  4. ,  2. ]])

In [73]:
#To replace the null values with mode values of respective column
imp=SimpleImputer(strategy='median')
imp.fit_transform(data)

array([[ 1. ,  3.5,  2. ],
       [ 2. ,  3. ,  2. ],
       [-1. ,  4. ,  2. ]])

In [74]:
#To replace the null values with most_frequent values of respective column
imp=SimpleImputer(strategy='most_frequent')
imp.fit_transform(data)

array([[ 1.,  3.,  2.],
       [ 2.,  3.,  2.],
       [-1.,  4.,  2.]])

In [75]:
#Max Normalizer
from sklearn.preprocessing import Normalizer
data=np.array([[1.0,2.0],[2.0,3.0]])
n_max=Normalizer(norm="max")
n_max.fit_transform(data)


array([[0.5       , 1.        ],
       [0.66666667, 1.        ]])

In [76]:
#L1 Normalizer
n_l1=Normalizer(norm="l1")
n_l1.fit_transform(data)

array([[0.33333333, 0.66666667],
       [0.4       , 0.6       ]])

In [77]:
#L2 Normalizer
n_l2=Normalizer(norm="l2")
n_l2.fit_transform(data)

array([[0.4472136 , 0.89442719],
       [0.5547002 , 0.83205029]])

In [78]:
#To remove feature whose variance in under Threshold
from sklearn.feature_selection import VarianceThreshold
X[0:3,:]

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, 0.0000e+00, 5.3800e-01,
        6.5750e+00, 6.5200e+01, 4.0900e+00, 1.0000e+00, 2.9600e+02,
        1.5300e+01, 3.9690e+02, 4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        6.4210e+00, 7.8900e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9690e+02, 9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        7.1850e+00, 6.1100e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9283e+02, 4.0300e+00]])

In [79]:
vt=VarianceThreshold(threshold=1.5)
X_t=vt.fit_transform(X)
X_t[0:3,:]

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, 6.5200e+01, 4.0900e+00,
        1.0000e+00, 2.9600e+02, 1.5300e+01, 3.9690e+02, 4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, 7.8900e+01, 4.9671e+00,
        2.0000e+00, 2.4200e+02, 1.7800e+01, 3.9690e+02, 9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, 6.1100e+01, 4.9671e+00,
        2.0000e+00, 2.4200e+02, 1.7800e+01, 3.9283e+02, 4.0300e+00]])

In [1]:
#Dictonary 
data=[
    {'price':850000,'rooms':4,'neighborhood':'Queen Anne'},
    {'price':850000,'rooms':3,'neighborhood':'Fremont'},
    {'price':650000,'rooms':3,'neighborhood':'Wallingford'},
    {'price':600000,'rooms':2,'neighborhood':'Fremont'},   
]

In [2]:
#Use DictVectorizer to map feature mappings to vector
from sklearn.feature_extraction import DictVectorizer
vec=DictVectorizer(sparse=False, dtype=int)
vec.fit_transform(data)

array([[     0,      1,      0, 850000,      4],
       [     1,      0,      0, 850000,      3],
       [     0,      0,      1, 650000,      3],
       [     1,      0,      0, 600000,      2]])

In [3]:
vec.get_feature_names()          # Get the names of features

['neighborhood=Fremont',
 'neighborhood=Queen Anne',
 'neighborhood=Wallingford',
 'price',
 'rooms']

In [83]:
vec=DictVectorizer(sparse=True, dtype=int)
d=vec.fit_transform(data)                        #To fit data into DictVectorizer

In [84]:
print(d)

  (0, 1)	1
  (0, 3)	850000
  (0, 4)	4
  (1, 0)	1
  (1, 3)	700000
  (1, 4)	3
  (2, 2)	1
  (2, 3)	650000
  (2, 4)	3
  (3, 0)	1
  (3, 3)	600000
  (3, 4)	2


In [4]:
# Array
sample = ['problem of evil',
         'evil of queen','horizon problem']

In [5]:
#CountVectorizer to get count of each word
from sklearn.feature_extraction.text import CountVectorizer

vec=CountVectorizer()
X=vec.fit_transform(sample)
X

<3x5 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [6]:
print(X)

  (0, 3)	1
  (0, 2)	1
  (0, 0)	1
  (1, 2)	1
  (1, 0)	1
  (1, 4)	1
  (2, 3)	1
  (2, 1)	1


In [7]:
#Display the count in DataFrame Format
import pandas as pd
pd.DataFrame(X.toarray(),columns=vec.get_feature_names())

evil  horizon  of  problem  queen
0     1        0   1        1      0
1     1        0   1        0      1
2     0        1   0        1      0

In [89]:
#Import TfidfVectorizer 
from sklearn.feature_extraction.text import TfidfVectorizer

vec=TfidfVectorizer()
X=vec.fit_transform(sample)
pd.DataFrame(X.toarray(),columns=vec.get_feature_names())

evil   horizon        of   problem     queen
0  0.517856  0.000000  0.680919  0.517856  0.000000
1  0.605349  0.000000  0.000000  0.000000  0.795961
2  0.000000  0.795961  0.000000  0.605349  0.000000

In [90]:
#To create pipeline

from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from numpy import nan

X=np.array([[nan,0,3],[3,7,9],[3,5,2],[4,nan,6],[8,8,1]])
y=np.array([14,16,-1,8,-5])

#Pipeline to first replace NULL values with mean then add Polynomial Features and later Apply linear Regression

model=make_pipeline(SimpleImputer(strategy='mean'),PolynomialFeatures(degree=2),LinearRegression())


In [91]:
model.fit(X,y)
print(model)

Pipeline(memory=None,
         steps=[('simpleimputer',
                 SimpleImputer(add_indicator=False, copy=True, fill_value=None,
                               missing_values=nan, strategy='mean',
                               verbose=0)),
                ('polynomialfeatures',
                 PolynomialFeatures(degree=2, include_bias=True,
                                    interaction_only=False, order='C')),
                ('linearregression',
                 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
                                  normalize=False))],
         verbose=False)
