In [1]:
#Import libraries
import numpy as np
import pandas as pd
import sklearn

In [2]:
#Read dataset
dataset=pd.read_csv("Datasets\\knn.csv")
print(dataset)

   X  Y Class_Label
0  2  4           N
1  4  6           N
2  4  4           P
3  4  2           N
4  6  4           N
5  6  2           P


In [3]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,2].values

In [4]:
print(x)

[[2 4]
 [4 6]
 [4 4]
 [4 2]
 [6 4]
 [6 2]]


In [5]:
print(y)

['N' 'N' 'P' 'N' 'N' 'P']


In [6]:
#Import KNN Classifier
from sklearn.neighbors import KNeighborsClassifier

In [7]:
#for k=3 generate KNN
classifier=KNeighborsClassifier(n_neighbors=3)

In [8]:
#fit the model
classifier.fit(x,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [9]:
x_test=np.array([6,6])

In [10]:
#Predict the class label for [6,6]
y_predict=classifier.predict([x_test])

In [11]:
print(y_predict)

['N']


In [12]:
classifier=KNeighborsClassifier(n_neighbors=3,weights='distance')

In [13]:
classifier.fit(x,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='distance')

In [14]:
y_predict=classifier.predict([x_test])
print(y_predict)

['N']


In [15]:
#Import libraries
import numpy as np
import pandas as pd
import sklearn
from sklearn.neighbors import KNeighborsClassifier

df=pd.read_csv("Datasets\\knn1.csv")
df

Height  Age  Weight
0    5.00   45      77
1    5.11   26      47
2    5.60   30      55
3    5.90   34      59
4    4.80   40      72
5    5.80   36      60
6    5.30   19      40
7    5.80   28      60
8    5.50   23      45
9    5.60   32      58

In [16]:
x=df.iloc[:,:-1].values
x

array([[ 5.  , 45.  ],
       [ 5.11, 26.  ],
       [ 5.6 , 30.  ],
       [ 5.9 , 34.  ],
       [ 4.8 , 40.  ],
       [ 5.8 , 36.  ],
       [ 5.3 , 19.  ],
       [ 5.8 , 28.  ],
       [ 5.5 , 23.  ],
       [ 5.6 , 32.  ]])

In [17]:
y=df.iloc[:,-1].values
y

array([77, 47, 55, 59, 72, 60, 40, 60, 45, 58], dtype=int64)

In [18]:
#Apply KNN for Regression
classifier=KNeighborsClassifier(n_neighbors=3)
classifier.fit(x,y)
x_test=np.array([5.50,26])
y_predict=classifier.predict([x_test])
print(y_predict)

[45]
